# Generated by Django 6.0.1 on 2026-01-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("first_habit", "First Habit Created"),
                            ("streak_3", "3 Day Streak"),
                            ("streak_7", "7 Day Streak"),
                            ("streak_14", "2 Week Streak"),
                            ("streak_30", "30 Day Streak"),
                            ("streak_100", "100 Day Streak"),
                            ("complete_10", "10 Completions"),
                            ("complete_50", "50 Completions"),
                            ("complete_100", "100 Completions"),
                            ("complete_500", "500 Completions"),
                            ("perfect_week", "Perfect Week"),
                            ("perfect_month", "Perfect Month"),
                        ],
                        max_length=50,
                    ),
                ),
                ("earned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_date"],
                "unique_together": {("user", "achievement_type")},
            },
        ),
    ]
